version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Desactiva seguridad para facilitar pruebas
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    platform: linux/arm64  # Necesario para chip M1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    platform: linux/arm64  # Necesario para chip M1

volumes:
  esdata:
